// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzpfjmybMATOwxqU4JJuI6qlwIqZhZsM',
    appId: '1:665229797732:web:89a460dbc44516cc4af271',
    messagingSenderId: '665229797732',
    projectId: 'flutter-chat-app-63ba0',
    authDomain: 'flutter-chat-app-63ba0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-63ba0.firebasestorage.app',
    measurementId: 'G-DZQCE0N0FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeyW91yVGVMrJSf69Ebnx33UJR9QnS8Io',
    appId: '1:665229797732:android:1aa0f319b9f5c19b4af271',
    messagingSenderId: '665229797732',
    projectId: 'flutter-chat-app-63ba0',
    storageBucket: 'flutter-chat-app-63ba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNs744TLb_CJoHhbf119dMAIowp6YobT0',
    appId: '1:665229797732:ios:f6599e4efc7918da4af271',
    messagingSenderId: '665229797732',
    projectId: 'flutter-chat-app-63ba0',
    storageBucket: 'flutter-chat-app-63ba0.firebasestorage.app',
    iosBundleId: 'com.example.chatbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhzpfjmybMATOwxqU4JJuI6qlwIqZhZsM',
    appId: '1:665229797732:web:02c621dd5ff3a5724af271',
    messagingSenderId: '665229797732',
    projectId: 'flutter-chat-app-63ba0',
    authDomain: 'flutter-chat-app-63ba0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-63ba0.firebasestorage.app',
    measurementId: 'G-FPPGZ6QMND',
  );

}